---
name: Publish Dev Container Image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t iypetrov/devcontainer:${{ github.ref_name }} .

      - name: Tag & Push to Docker Hub
        run: |
          docker tag iypetrov/devcontainer:${{ github.ref_name }} iypetrov/devcontainer:${{ github.ref_name }}
          docker push iypetrov/devcontainer:${{ github.ref_name }}
