---
name: Publish Dev Container Image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR with PAT
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build image
        run: |
          docker build \
            --build-arg ANSIBLE_VAULT_PASSWORD="${{ secrets.ANSIBLE_VAULT_PASSWORD }}" \
            -t iypetrov/devcontainer:${{ github.ref_name }} .

      - name: Tag & Push to GHCR 
        run: |
          docker tag iypetrov/devcontainer:${{ github.ref_name }} ghcr.io/iypetrov/devcontainer:${{ github.ref_name }}
          docker push ghcr.io/iypetrov/devcontainer:${{ github.ref_name }}
