---
name: Publish Dev Container Image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ -z "$TAG" ]]; then
            echo "Failed to extract TAG from GITHUB_REF"
            exit 1
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Extracted TAG: $TAG"
  
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.TAG }}
